### ISSUE TITLE
Question about timezone

### ISSUE THREAD

**Issue by Edo78** [giuseppeg88/node-red-contrib-thermostat-scheduler#13]
I see that you localized every string as italian so I wonder why you chose the rimezone `ETC/GMT` instead of `Europe/Rome`

**Comment by Edo78** [comment]
In another node you use `UTC`
I struggle to find a rationale in this. Can you help me understand?

**Comment by giuseppeg88** [comment]
18350972e6ec603ba4edf5e0c0d85de86b12ee60
