### ISSUE TITLE
How to put it in a lovalace UI

### ISSUE THREAD

**Issue by MarcinHaduch** [giuseppeg88/node-red-contrib-thermostat-scheduler#14]
Could you please add some info to a instruction in read.me how to set it up in a lovelace UI in Home assisntant?

**Comment by Timsche2210** [comment]
I would also appreciate this.
I am to dumb to add this to loveplace :/

**Comment by giuseppeg88** [comment]
Somebody use the [“iframe card”](https://www.home-assistant.io/integrations/panel_iframe/) (with URL _http://your_home_assistant_IP_address:1880/endpoint/ui/_) to display this dashboard in lovelace.

**Comment by nicw** [comment]
Wow, I never would have guessed this. Can this please be added to the readme please? It is truly the final step of this great plugin, and just needs to be noted.
