### ISSUE TITLE
Messy graphic

### ISSUE THREAD

**Issue by Edo78** [giuseppeg88/node-red-contrib-thermostat-scheduler#3]
The first time opening the dashboard it show everything at the same time
![image](https://user-images.githubusercontent.com/3602209/99985566-65c68300-2dae-11eb-97fa-6bc21393e418.png)
After clicking on all the "torna alla home" it begin to works as intended.

**Comment by giuseppeg88** [comment]
18350972e6ec603ba4edf5e0c0d85de86b12ee60
