### ISSUE TITLE
No widget

### ISSUE THREAD

**Issue by SamBozman** [giuseppeg88/node-red-contrib-thermostat-scheduler#6]
I followed the instructions and the red-node flow seems to be running with no errors but even though I have rebooted Home Assistant twice, I do not see a widget card for this flow. 
I re-read the documentation but do not see how to enable this card. If I add a standard thermostat card, I just get the same basic one I have been using.

**Comment by giuseppeg88** [comment]
To open the Node-RED UI, type your Home Assistant IP address in a web browser followed by "**:1880/endpoint/ui/**" as shown below:

`http://your_home_assistant_IP_address:1880/endpoint/ui/`
